version: "3.8"

# x-common-variables: &common-variables
#   MYSQL_DATABASE: books
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "81:81"
    volumes:
      - "./ssl/:/var/nginx/"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - ./client:/app

  api:
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8080"
